Choose ECLIPSE_INSTALLER based on (OSTYPE,MACHINE)
For the time being the following configurations are supported:
* (GNU/Linux, i686)
* (GNU/Linux, x86_64)

Signed-off-by: Gianpaolo Macario <gianpaolo_macario@mentor.com>

diff --git a/CONFIG b/CONFIG
--- a/CONFIG
+++ b/CONFIG
@@ -21,11 +21,25 @@ WORKSPACE_DIR=$HOME/workspace
 # be reset to /vagrant instead
 DOWNLOAD_DIR=/tmp
 
-ECLIPSE_INSTALLER="http://ftp.fau.de/eclipse/technology/epp/downloads/release/kepler/R/eclipse-dsl-kepler-R-linux-gtk-x86_64.tar.gz"
+OSTYPE=$(uname -o)
+MACHINE=$(uname -m)
 
 # NOTE: You can set _MD5 variables to empty to skip MD5 check
 # (just remove the assignment altogether)
-ECLIPSE_MD5=cd6d141af286ea06988b3710f6b9c19c
+if [ "$OSTYPE" = "GNU/Linux" -a "$MACHINE" = "i686" ]; then
+    ECLIPSE_INSTALLER="http://ftp.fau.de/eclipse/technology/epp/downloads/release/kepler/R/eclipse-dsl-kepler-R-linux-gtk.tar.gz"
+    ECLIPSE_MD5=881466e4f7ee0b83e9406e6516d57b95
+elif [ "$OSTYPE" = "GNU/Linux" -a "$MACHINE" = "x86_64" ]; then
+    ECLIPSE_INSTALLER="http://ftp.fau.de/eclipse/technology/epp/downloads/release/kepler/R/eclipse-dsl-kepler-R-linux-gtk-x86_64.tar.gz"
+    ECLIPSE_MD5=cd6d141af286ea06988b3710f6b9c19c
+# elif [ "$OSTYPE" = "???" -a "$MACHINE" = "???" ]; then
+    # TODO: Handle case (MacOSX, etc.)
+    #ECLIPSE_INSTALLER=???
+    #ECLIPSE_MD5=???
+else
+    echo "ERROR: Unknown (OSTYPE=$OSTYPE, MACHINE=$MACHINE)" >/dev/stderr
+    exit 1
+fi
 
 # D-Bus EMF model ---------------------------------------------------
 
@@ -84,3 +98,5 @@ org.franca.generators.source
 # FRANCA EXAMPLES ----------------------------------------------------
 
 EXAMPLES_URL=https://franca.eclipselabs.org.codespot.com/files/org_franca_examples_src_2013-09-26.zip
+
+# === EOF ===
